spring:
  application:
    name: autoapply-backend
  profiles:
    default: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health
