package com.autoapply.audit;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    REGISTER,
    TOKEN_REFRESHED,
    PASSWORD_CHANGED,
    PROFILE_UPDATED,
    RESUME_UPLOADED,
    RESUME_PARSED,

    SETTING_UPDATED,
    SETTING_RESET,

    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    USER_ENABLED,
    USER_DELETED,
    USER_ROLE_CHANGED,
    USER_UNLOCKED,

    JOB_SOURCE_CREATED,
    JOB_SOURCE_UPDATED,
    JOB_SOURCE_DELETED,
    JOB_SOURCE_TESTED,
    JOBS_FETCHED,
    JOBS_PURGED,

    PORTAL_CONFIG_CREATED,
    PORTAL_CONFIG_UPDATED,
    PORTAL_CONFIG_DELETED,

    PROMPT_UPDATED,

    MATCHING_RUN,
    AUTO_APPLY_RUN,
    APPLICATION_SUBMITTED,
    APPLICATION_FAILED,
    APPLICATION_RETRIED,

    SCHEDULE_UPDATED,
    SCHEDULE_TRIGGERED,
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED,

    ADMIN_ACTION
}
