server:
  port: 8081

spring:
  application:
    name: core-api
  profiles:
    default: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health
